### ISSUE TITLE
importing works only for installed packages

### ISSUE THREAD

**Issue by den-run-ai** [fkarb/pythonnet_old#10]
I tried importing module found in Python path and this returned null. But importing installed packages such as numpy, sympy, scipy works. Also I tried installing my module as a package, but this return null again, although Python interpreter does not complain.

**Comment by den-run-ai** [comment]
I understood how this import works, but this requires complicated installation for modules/packages with absolute_import and **init**.py files in package directories.

**Comment by tonyroberts** [comment]
Not sure what the issue you're talking about is to be honest... this is probably a question better asked on the mailing list of as an issue to the main pythonnet project.

If it's an issue specific to this fork please try and explain exactly what the issue is, preferably with a fix (pull request) or an example or unit test demonstrating the problem.
